openapi: 3.0.1
info:
  description: Update a customer's details
  title: updcust
  version: 1.0.0
servers:
- url: /
paths:
  /update:
    put:
      operationId: putCScustupd
      parameters:
      - explode: false
        in: header
        name: Authorization
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/putCScustupd_request'
        description: request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/putCScustupd_response_200'
          description: OK
      tags:
      - customer
      x-codegen-request-body-name: putCScustupd_request
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: customer
components:
  schemas:
    putCScustupd_request:
      properties:
        UpdCust:
          $ref: '#/components/schemas/putCScustupd_request_UpdCust'
      type: object
    putCScustupd_response_200:
      example:
        UpdCust:
          ApiCustno: ApiCustno
          ApiName: ApiName
          ApiAddress: ApiAddress
      properties:
        UpdCust:
          $ref: '#/components/schemas/putCScustupd_request_UpdCust'
      type: object
    putCScustupd_request_UpdCust:
      example:
        ApiCustno: ApiCustno
        ApiName: ApiName
        ApiAddress: ApiAddress
      properties:
        ApiCustno:
          maxLength: 10
          type: string
        ApiName:
          maxLength: 60
          type: string
        ApiAddress:
          maxLength: 160
          type: string
      type: object
x-original-swagger-version: "2.0"

