version: "3.2"
services:
    zosConnect:
        image: icr.io/zosconnect/ibm-zcon-designer:3.0.70
        environment:
            - CICS_USER=<cicsUsername>
            - CICS_PASSWORD=<cicsPassword>
            - CICS_HOST=esysmvs2.ztec.dmz
            - CICS_PORT=7082
            - HTTP_PORT=9080
        ports:
            - "9443:9443"
            - "9080:9080"
        volumes:
            - ./cbsa:/workspace/project
            - ./logs/:/logs/
            - ./certs:/config/resources/security/:ro